function Fw = fftwfield(Opts)
% Calculate the Forier transform of sepcific fields.
    %% ============================== Default input parameters ============================== %%
    arguments
        Opts.fnum = 'all';              % fnum should be an Arithmetic progression to perform temporal fft.
        Opts.field = 'all';             % cell array with field names in struct F (generated by loadfield.m)
        Opts.save = 'gather';           % gather, split, none
        Opts.reshape = true;
        Opts.wshift = false;            % if shift in frequency space
        Opts.checkmem = false;          % if check memory
    end
    Memlim = 0.8;                       % Percentage of available memory
    e = 1.6021766208e-19;
    me = 9.10938291e-31;

    %% ============================== Load all available files ============================== %%
    Fname = dir('field*.dat');
    if isempty(Fname)
        fprintf('-------------No field*****.dat file found-------------\n');
        return;
    end

    %% ============================== Check memory ============================== %%
    F = loadfield(Fname(1).name);
    if ~strcmpi(Opts.fnum, 'all')
        F = F(fnum);
    end
    Nfile = numel(Fname);
    whosF = whos('F');
    bytesF = whosF.bytes*Nfile;
    if Opts.checkmem
        Memory = memory;
        MaxBytes = Memory.MaxPossibleArrayBytes*Memlim;
        MemAvl = MaxBytes/bytesF;                      % MemAvl > 2 : able to gather all fields simutanuously
    else
        MemAvl = 3;
    end
    
    %% ============================== Gather fields and fft ============================== %%
    % Specify fields to process
    if ~strcmpi(Opts.field, 'all')
        FldName = Opts.field;
    else
        FldName = fieldnames(F);
        FldName = FldName(14:end);                       % Field arrays start from field 14 of struct F.
    end
    Nfield = numel(FldName);
    % x, y, z, dr, t, dt, kx, ky, kz, dk, w, dw are initialized in
    F0 = wk(F, Nfile);
    % Reshape parameters
    shape0 = [F.nx, F.ny, F.nz, Nfile];
    shape = [];
    for k = 1:4
        if shape0(k) > 1
            shape = [shape, shape0(k)];
        end
    end
    if MemAvl > 2
        % -------------------- Create field array -------------------- %
        Fw = F0;
        for k = 1:Nfield
            Fw.(FldName{k}) = repmat(zeros(size(F.(FldName{k}))), 1, 1, 1, Nfile);
        end
        % -------------------- Load data -------------------- %
        for j = 1:Nfile
            F = loadfield(Fname(j).name);
            wci = e*F.parray(12)*1e-4/(F.parray(3)/F.parray(2)*me);
            Fw.t(j) = F.stime/wci;
            for k = 1:Nfield
                Fw.(FldName{k})(:, :, :, j) = F.(FldName{k});
            end
        end
        % -------------------- Process data -------------------- %
        % Calculate w, dw, dt
        [Fw.w, Fw.dw, Fw.dt] = wdwdt(Fw.t, Opts.wshift);
        % fft
        for k = 1:Nfield
            Fw.(FldName{k}) = fftcalcwk(Fw.(FldName{k}), [Fw.dr, Fw.dt], Opts.wshift);
        end
        % Reshape
        if Opts.reshape
            for k = 1:Nfield
                Fw.(FldName{k}) = reshape(Fw.(FldName{k}), shape);
            end
        end
        % -------------------- Save data -------------------- %
        if strcmpi(Opts.save, 'gather')
            save('Fwk', "Fw", '-mat');
        elseif strcmpi(Opts.save, 'split')
            for k = 1:Nfield
                Fk = F0;
                Fk.t = Fw.t;
                Fk.dt = Fw.dt;
                Fk.w = Fw.w;
                Fk.dw = Fw.dw;
                Fk.(FldName{k}) = Fw.(FldName{k});
                save([FldName{k}, 'wk'], "Fk", '-mat');
            end
        elseif strcmpi(Opts.save, 'none')
        end
    else
        for k = 1:Nfield
            % -------------------- Create field array -------------------- %
            Fk = F0;
            Fk.(FldName{k}) = repmat(zeros(size(F.(FldName{k}))), 1, 1, 1, Nfile);
            % -------------------- Load data -------------------- %
            for j = 1:Nfile
                F = loadfield(Fname(j).name);
                if k == 1
                    Fk.t(j) = F.stime*F.parray(3)/F.parray(2)/(F.parray(12)*1e-4)*me/e;
                end
                Fk.(FldName{k})(:, :, :, j) = F.(FldName{k});
            end
            % -------------------- Process data -------------------- %
            % Calculate w, dw, dt
            if k == 1
                [Fk.w, Fk.dw, Fk.dt] = wdwdt(Fk.t, Opts.wshift);
                F0.t = Fk.t;
                F0.dt = Fk.dt;
                F0.w = Fk.w;
                F0.dw = Fk.dw;
            end
            % fft
            Fk.(FldName{k}) = fftcalcwk(Fk.(FldName{k}), [Fk.dr, Fk.dt], Opts.wshift);
            % Reshape
            if Opts.reshape
                Fk.(FldName{k}) = reshape(Fk.(FldName{k}), shape);
            end
            % -------------------- Save data -------------------- %
            if strcmpi(Opts.save, 'gather') || strcmpi(Opts.save, 'split')
                save([FldName{k}, 'wk'], "Fk", '-mat');
            elseif strcmpi(Opts.save, 'none')
            end
        end
        Fw = Fk;
    end
end

%% ============================== Get k, w ============================== %%
function Fw = wk(F, nt)
% Transform (x, y, z, t) to (kx, ky, kz, w)
    Fw = struct;
    % x, y, z, t
    Fw.x = F.x;                      dx = mean(F.x(2:end) - F.x(1:end-1), 'all');
    Fw.y = F.y;                      dy = mean(F.y(2:end) - F.y(1:end-1), 'all');
    Fw.z = F.z;                      dz = mean(F.z(2:end) - F.z(1:end-1), 'all');
    Fw.dr = [dx, dy, dz];       clear('dx', 'dy', 'dz');
    Fw.t = zeros(1, nt);
    Fw.dt = 0;
    % kx, ky, kx, w
    DK = zeros(1, 3);
    Kdomain = cell(1, 3);
    fsize = [F.nx, F.ny, F.nz];
    dimexist = fsize > 1;
    r = {F.x, F.y, F.z};
    for k = 1:3
        if dimexist(k)
            dkk = 2*pi/fsize(k)/Fw.dr(k);
            DK(k) = dkk;
            Kdomain{k} = ((1:fsize(k)) - (fsize(k) + 1)/2.0)*dkk;
            Kdomain{k} = reshape(Kdomain{k}, size(r{k}));
        else
            Kdomain{k} = 0;
        end
    end
    Fw.kx = Kdomain{1};
    Fw.ky = Kdomain{2};
    Fw.kz = Kdomain{3};
    Fw.dk = DK;
    Fw.w = Fw.t;
    Fw.dw = 0;
end

function [w, dw, dt] = wdwdt(t, wshift)
% Transform t to w
    dt = (t(end) - t(1))/(numel(t) - 1);
    dw = 2*pi/dt/numel(t);
    if wshift
        w = ((1:numel(t)) - (numel(t) + 1)/2.0)*dw;
    else
        w = (0:numel(t)-1)*dw;
    end
end

%% ============================== Calculate fft ============================== %%
function k = fftcalcwk(x, dr, wshift)
% Multidimension Fourier tramsform.
% x : Field to be transformed.
% dr : Intervals of each dimension.
    k = x;
    for j = 1:4
        sizex = size(k, j);
        if sizex > 1
            k = fft(k, sizex, j)*dr(j);
        end
    end
    k = fftshift(k);
    if ~wshift
        k = fftshift(k, 4);
    end
end