function F = plotnprof(G, Gdata, Ps)
% Gdata : GENRAY data generated by GENRAY.load();
% Ps : particle struct array with field 'Name' or cell array containing names of particles.
    % F = G;
    if nargin > 2
        figure(G);
    else
        F = figure;
    end
    % Set names of particle species
    Name = cell(1, Gdata.nbulk);
    if isa(Ps, 'struct');
        if numel(Ps) < Gdata.nbulk
            error('In GENRAY.plotnprof : Not enough particle names.\n');
        end
        for k = 1:Gdata.nbulk
            Name{k} = Ps{k}.Name;
        end
    elseif isa(Ps, 'cell')
        Name = Ps;
    else
        error('In GENRAY.plotnprof : Error input particle names.\n');
    end
    % Distinguish bulk species and minor species.
    maxn = nan(1, Gdata.nbulk);
    for k = 1:Gdata.nbulk
        maxn(k) = max(Gdata.densprof(:, k));
    end
    ratio = ceil(log10(maxn./max(maxn)));
    ifminor = ratio < 0;
    for k = 1:Gdata.nbulk
        if ~ifminor
            plot(data.rho_bin, data.densprof(:, k)/1e20, 'LineWidth', 1, 'DisplayName', Name{k});
        else
            plot(data.rho_bin, data.densprof(:, k)*10^(-ratio(k)), 'LineWidth', 1, 'DisplayName', Name{k});
        end
    end
end